name: Deploy to GitHub Pages

on:
  push:
    branches:
      - development

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Make demo page
        run: |
          pip install .
          make -C docs revealjs
          touch docs/_build/revealjs/.nojekyll
      - name: Deploy to GitHub Pages
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: docs/_build/revealjs/
          GH_PAT: ${{ secrets.GH_PAT }}
